apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 056671487005.dkr.ecr.ap-northeast-2.amazonaws.com/my_project
  newName: 056671487005.dkr.ecr.ap-northeast-2.amazonaws.com/my_project
  newTag: f03b36a1
resources:
- ../../base
