#spring:
#  h2:
#    console:
#      enabled: true

#spring:
#  datasource:
#      url: jdbc:mysql://localhost:3306/batch_test
#      username: root
#      password: root
#      driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  batch:
    job:
      enabled: false

#spring:
#  datasource:
#    hikari:
#      jdbc-url: jdbc:mysql://localhost:3306/batch_test
#      username: root
#      password: root
#      driver-class-name: com.mysql.cj.jdbc.Driver
#  sql:
#    init:
#      schema-locations: classpath:/org/springframework/batch/core/schema-h2.sql

#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true